name: document
on:
  push:
    branches:
      - master
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: swatinem/rust-cache@v2
      - uses: actions/configure-pages@v5
      - uses: homebrew/actions/setup-homebrew@master
      - run: tools/setup.sh
      - run: cargo clean --doc
      - run: cargo doc --document-private-items
      - name: Generate index.html file
        run: |
            echo "<meta http-equiv=refresh content=0;url=tblgen-alt/index.html>" > target/doc/index.html
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./target/doc
  deploy:
      needs: build
      runs-on: ubuntu-latest
      steps:
      - name: Deploy documentation
        id: pages
        uses: actions/deploy-pages@v4
