name: test
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          # TODO Enable macOS.
          # - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: swatinem/rust-cache@v2
      - uses: homebrew/actions/setup-homebrew@master
      - run: tools/setup.sh
      - run: cargo build
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          # TODO Enable macOS.
          # - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: swatinem/rust-cache@v2
      - uses: homebrew/actions/setup-homebrew@master
      - run: tools/setup.sh
      - run: cargo test
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: swatinem/rust-cache@v2
      - uses: homebrew/actions/setup-homebrew@master
      - run: tools/setup.sh
      - run: cargo clippy -- -D warnings
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo fmt --check
      - run: clang-format --dry-run -Werror wrapper.h $(git ls-files cc)
